# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86fd99b9e7ad06daa42aad91164efa406c82e2d95b623e91d509c5fc7c7cbe3b8804925b128824d385a908e44d46fbe59b7463cf4457ca09a0a78715778813ed

test:
  secret_key_base: 98bc8cb54122b72541fc75468d79ec5e211fad80307854ebb29a4739c11eeb1c047655b023a1d9ea19326db2678dd55bf374c6458021907f0d88344b59fc778b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
