# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 503e7e18a20e9141ce64507a0c155728eae0061faed70f8a20092f3933bf6322184f714026a3e6a6c16f60c61f2b8014963ff10e31e9767d29485646acc94ab0

test:
  secret_key_base: 7933946d84b27fcc16e16320f5235a97512452e9a6d49dad8678c8e66d72a8092125e8588b38c27dae2524cd11efc656782878b00fd4588fa594dc28473c586c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
