# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b9545a1cc6a3f5cd01ca1a486f467d51e80c56da5d97d249318bf8d53ccb8b6f7c6bd4e9767c9012400f3b8378508c019ac15f1add132ce02cc4883768cae29

test:
  secret_key_base: 8d5d629f35fbbc784ecc18a30ee54c86d710c84ec71de64adec8e234a00120c9c81045b93cdfdd632662672f8d9138cd9211f15e8051405097c9a407479c50af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
